package org.apache.tapestry.finder.entities.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.tapestry.finder.entities.ComponentEntry;

/**
 * Class _TapestryVersion was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _TapestryVersion extends CayenneDataObject {

    public static final String DESCRIPTION_PROPERTY = "description";
    public static final String ID_PROPERTY = "id";
    public static final String NAME_PROPERTY = "name";
    public static final String SORT_BY_PROPERTY = "sortBy";
    public static final String COMPONENTS_SINCE_PROPERTY = "componentsSince";
    public static final String COMPONENTS_UNTIL_PROPERTY = "componentsUntil";

    public static final String ID_PK_COLUMN = "id";

    public void setDescription(String description) {
        writeProperty("description", description);
    }
    public String getDescription() {
        return (String)readProperty("description");
    }

    public void setId(Long id) {
        writeProperty("id", id);
    }
    public Long getId() {
        return (Long)readProperty("id");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void setSortBy(Integer sortBy) {
        writeProperty("sortBy", sortBy);
    }
    public Integer getSortBy() {
        return (Integer)readProperty("sortBy");
    }

    public void addToComponentsSince(ComponentEntry obj) {
        addToManyTarget("componentsSince", obj, true);
    }
    public void removeFromComponentsSince(ComponentEntry obj) {
        removeToManyTarget("componentsSince", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<ComponentEntry> getComponentsSince() {
        return (List<ComponentEntry>)readProperty("componentsSince");
    }


    public void addToComponentsUntil(ComponentEntry obj) {
        addToManyTarget("componentsUntil", obj, true);
    }
    public void removeFromComponentsUntil(ComponentEntry obj) {
        removeToManyTarget("componentsUntil", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<ComponentEntry> getComponentsUntil() {
        return (List<ComponentEntry>)readProperty("componentsUntil");
    }


}
