CREATE TABLE COMPONENTENTRY (
		DEMONSTRATIONURL VARCHAR(1024),
		DESCRIPTION VARCHAR(4096) NOT NULL,
		DOCUMENTATIONURL VARCHAR(1024),
		ENABLED SMALLINT NOT NULL,
		FIRSTAVAILABLE DATE,
		ID INTEGER DEFAULT GENERATED_BY_DEFAULT NOT NULL GENERATED ALWAYS AS IDENTITY  (START WITH 1 ,INCREMENT BY 4),
		NAME VARCHAR(100) NOT NULL
	);

CREATE TABLE SYSCONGLOMERATES (
		SCHEMAID CHAR(36) NOT NULL,
		TABLEID CHAR(36) NOT NULL,
		CONGLOMERATENUMBER BIGINT NOT NULL,
		CONGLOMERATENAME VARCHAR(128),
		ISINDEX null NOT NULL,
		DESCRIPTOR null,
		ISCONSTRAINT null,
		CONGLOMERATEID CHAR(36) NOT NULL
	);

CREATE TABLE SYSROUTINEPERMS (
		ROUTINEPERMSID CHAR(36) NOT NULL,
		GRANTEE VARCHAR(128) NOT NULL,
		GRANTOR VARCHAR(128) NOT NULL,
		ALIASID CHAR(36) NOT NULL,
		GRANTOPTION CHAR(1) NOT NULL
	);

CREATE TABLE SYSVIEWS (
		TABLEID CHAR(36) NOT NULL,
		VIEWDEFINITION LONG VARCHAR NOT NULL,
		CHECKOPTION CHAR(1) NOT NULL,
		COMPILATIONSCHEMAID CHAR(36)
	);

CREATE TABLE SYSSTATISTICS (
		STATID CHAR(36) NOT NULL,
		REFERENCEID CHAR(36) NOT NULL,
		TABLEID CHAR(36) NOT NULL,
		CREATIONTIMESTAMP TIMESTAMP NOT NULL,
		TYPE CHAR(1) NOT NULL,
		VALID null NOT NULL,
		COLCOUNT INTEGER NOT NULL,
		STATISTICS null NOT NULL
	);

CREATE TABLE SYSDEPENDS (
		DEPENDENTID CHAR(36) NOT NULL,
		DEPENDENTFINDER null NOT NULL,
		PROVIDERID CHAR(36) NOT NULL,
		PROVIDERFINDER null NOT NULL
	);

CREATE TABLE CONF (
		ID INTEGER NOT NULL,
		NAME VARCHAR(32) NOT NULL,
		VALUE VARCHAR(256)
	);

CREATE TABLE SYSTABLES (
		TABLEID CHAR(36) NOT NULL,
		TABLENAME VARCHAR(128) NOT NULL,
		TABLETYPE CHAR(1) NOT NULL,
		SCHEMAID CHAR(36) NOT NULL,
		LOCKGRANULARITY CHAR(1) NOT NULL
	);

CREATE TABLE AUTO_PK_SUPPORT (
		TABLE_NAME CHAR(100) NOT NULL,
		NEXT_ID BIGINT NOT NULL
	);

CREATE TABLE ROLE (
		DESCRIPTION VARCHAR(1024) NOT NULL,
		ENABLED SMALLINT NOT NULL,
		ID INTEGER DEFAULT GENERATED_BY_DEFAULT NOT NULL GENERATED ALWAYS AS IDENTITY  (START WITH 1 ,INCREMENT BY 5),
		NAME VARCHAR(256) NOT NULL
	);

CREATE TABLE SYSCOLPERMS (
		COLPERMSID CHAR(36) NOT NULL,
		GRANTEE VARCHAR(128) NOT NULL,
		GRANTOR VARCHAR(128) NOT NULL,
		TABLEID CHAR(36) NOT NULL,
		TYPE CHAR(1) NOT NULL,
		COLUMNS null NOT NULL
	);

CREATE TABLE SYSTRIGGERS (
		TRIGGERID CHAR(36) NOT NULL,
		TRIGGERNAME VARCHAR(128) NOT NULL,
		SCHEMAID CHAR(36) NOT NULL,
		CREATIONTIMESTAMP TIMESTAMP NOT NULL,
		EVENT CHAR(1) NOT NULL,
		FIRINGTIME CHAR(1) NOT NULL,
		TYPE CHAR(1) NOT NULL,
		STATE CHAR(1) NOT NULL,
		TABLEID CHAR(36) NOT NULL,
		WHENSTMTID CHAR(36),
		ACTIONSTMTID CHAR(36),
		REFERENCEDCOLUMNS null,
		TRIGGERDEFINITION LONG VARCHAR,
		REFERENCINGOLD null,
		REFERENCINGNEW null,
		OLDREFERENCINGNAME VARCHAR(128),
		NEWREFERENCINGNAME VARCHAR(128)
	);

CREATE TABLE SYSTABLEPERMS (
		TABLEPERMSID CHAR(36) NOT NULL,
		GRANTEE VARCHAR(128) NOT NULL,
		GRANTOR VARCHAR(128) NOT NULL,
		TABLEID CHAR(36) NOT NULL,
		SELECTPRIV CHAR(1) NOT NULL,
		DELETEPRIV CHAR(1) NOT NULL,
		INSERTPRIV CHAR(1) NOT NULL,
		UPDATEPRIV CHAR(1) NOT NULL,
		REFERENCESPRIV CHAR(1) NOT NULL,
		TRIGGERPRIV CHAR(1) NOT NULL
	);

CREATE TABLE SYSSCHEMAS (
		SCHEMAID CHAR(36) NOT NULL,
		SCHEMANAME VARCHAR(128) NOT NULL,
		AUTHORIZATIONID VARCHAR(128) NOT NULL
	);

CREATE TABLE MODULEENTRY (
		DESCRIPTION VARCHAR(4096) NOT NULL,
		ENABLED SMALLINT NOT NULL,
		ID INTEGER DEFAULT GENERATED_BY_DEFAULT NOT NULL GENERATED ALWAYS AS IDENTITY  (START WITH 1 ,INCREMENT BY 8),
		NAME VARCHAR(128) NOT NULL,
		URL VARCHAR(1024)
	);

CREATE TABLE SYSPERMS (
		UUID CHAR(36) NOT NULL,
		OBJECTTYPE VARCHAR(36) NOT NULL,
		OBJECTID CHAR(36) NOT NULL,
		PERMISSION CHAR(36) NOT NULL,
		GRANTOR VARCHAR(128) NOT NULL,
		GRANTEE VARCHAR(128) NOT NULL,
		ISGRANTABLE CHAR(1) NOT NULL
	);

CREATE TABLE SYSSTATEMENTS (
		STMTID CHAR(36) NOT NULL,
		STMTNAME VARCHAR(128) NOT NULL,
		SCHEMAID CHAR(36) NOT NULL,
		TYPE CHAR(1) NOT NULL,
		VALID null NOT NULL,
		TEXT LONG VARCHAR NOT NULL,
		LASTCOMPILED TIMESTAMP,
		COMPILATIONSCHEMAID CHAR(36),
		USINGTEXT LONG VARCHAR
	);

CREATE TABLE SYSSEQUENCES (
		SEQUENCEID CHAR(36) NOT NULL,
		SEQUENCENAME VARCHAR(128) NOT NULL,
		SCHEMAID CHAR(36) NOT NULL,
		SEQUENCEDATATYPE null NOT NULL,
		CURRENTVALUE BIGINT,
		STARTVALUE BIGINT NOT NULL,
		MINIMUMVALUE BIGINT NOT NULL,
		MAXIMUMVALUE BIGINT NOT NULL,
		INCREMENT BIGINT NOT NULL,
		CYCLEOPTION CHAR(1) NOT NULL
	);

CREATE TABLE SYSCOLUMNS (
		REFERENCEID CHAR(36) NOT NULL,
		COLUMNNAME VARCHAR(128) NOT NULL,
		COLUMNNUMBER INTEGER NOT NULL,
		COLUMNDATATYPE null NOT NULL,
		COLUMNDEFAULT null,
		COLUMNDEFAULTID CHAR(36),
		AUTOINCREMENTVALUE BIGINT,
		AUTOINCREMENTSTART BIGINT,
		AUTOINCREMENTINC BIGINT
	);

CREATE TABLE SYSFILES (
		FILEID CHAR(36) NOT NULL,
		SCHEMAID CHAR(36) NOT NULL,
		FILENAME VARCHAR(128) NOT NULL,
		GENERATIONID BIGINT NOT NULL
	);

CREATE TABLE SYSROLES (
		UUID CHAR(36) NOT NULL,
		ROLEID VARCHAR(128) NOT NULL,
		GRANTEE VARCHAR(128) NOT NULL,
		GRANTOR VARCHAR(128) NOT NULL,
		WITHADMINOPTION CHAR(1) NOT NULL,
		ISDEF CHAR(1) NOT NULL
	);

CREATE TABLE SYSCONSTRAINTS (
		CONSTRAINTID CHAR(36) NOT NULL,
		TABLEID CHAR(36) NOT NULL,
		CONSTRAINTNAME VARCHAR(128) NOT NULL,
		TYPE CHAR(1) NOT NULL,
		SCHEMAID CHAR(36) NOT NULL,
		STATE CHAR(1) NOT NULL,
		REFERENCECOUNT INTEGER NOT NULL
	);

CREATE TABLE SYSKEYS (
		CONSTRAINTID CHAR(36) NOT NULL,
		CONGLOMERATEID CHAR(36) NOT NULL
	);

CREATE TABLE SYSALIASES (
		ALIASID CHAR(36) NOT NULL,
		ALIAS VARCHAR(128) NOT NULL,
		SCHEMAID CHAR(36),
		JAVACLASSNAME LONG VARCHAR NOT NULL,
		ALIASTYPE CHAR(1) NOT NULL,
		NAMESPACE CHAR(1) NOT NULL,
		SYSTEMALIAS null NOT NULL,
		ALIASINFO null,
		SPECIFICNAME VARCHAR(128) NOT NULL
	);

CREATE TABLE SYSDUMMY1 (
		IBMREQD CHAR(1)
	);

CREATE TABLE TAPESTRYVERSION (
		ID INTEGER NOT NULL,
		NAME VARCHAR(64) NOT NULL
	);

CREATE TABLE SYSCHECKS (
		CONSTRAINTID CHAR(36) NOT NULL,
		CHECKDEFINITION LONG VARCHAR NOT NULL,
		REFERENCEDCOLUMNS null NOT NULL
	);

CREATE TABLE SYSFOREIGNKEYS (
		CONSTRAINTID CHAR(36) NOT NULL,
		CONGLOMERATEID CHAR(36) NOT NULL,
		KEYCONSTRAINTID CHAR(36) NOT NULL,
		DELETERULE CHAR(1) NOT NULL,
		UPDATERULE CHAR(1) NOT NULL
	);

CREATE TABLE LICENSE (
		DESCRIPTION VARCHAR(1024),
		ID INTEGER DEFAULT GENERATED_BY_DEFAULT NOT NULL GENERATED ALWAYS AS IDENTITY  (START WITH 1 ,INCREMENT BY 3),
		NAME VARCHAR(127) NOT NULL
	);

CREATE UNIQUE INDEX SYSSEQUENCES_INDEX1 ON SYSSEQUENCES (null);

CREATE UNIQUE INDEX SYSTABLEPERMS_INDEX2 ON SYSTABLEPERMS (null);

CREATE INDEX SQL110709131720460 ON MODULEENTRY (null);

CREATE INDEX SQL110709131720330 ON COMPONENTENTRY (null);

CREATE UNIQUE INDEX SQL110709131719090 ON TAPESTRYVERSION (null);

CREATE UNIQUE INDEX SYSSCHEMAS_INDEX2 ON SYSSCHEMAS (null);

CREATE UNIQUE INDEX SQL110709131720470 ON AUTO_PK_SUPPORT (null);

CREATE INDEX SYSCONGLOMERATES_INDEX1 ON SYSCONGLOMERATES (null);

CREATE UNIQUE INDEX SYSSEQUENCES_INDEX2 ON SYSSEQUENCES (null);

CREATE UNIQUE INDEX SYSCOLPERMS_INDEX2 ON SYSCOLPERMS (null);

CREATE INDEX SYSROLES_INDEX2 ON SYSROLES (null);

CREATE UNIQUE INDEX SYSCOLUMNS_INDEX1 ON SYSCOLUMNS (null);

CREATE INDEX SYSTABLEPERMS_INDEX3 ON SYSTABLEPERMS (null);

CREATE UNIQUE INDEX SYSVIEWS_INDEX1 ON SYSVIEWS (null);

CREATE UNIQUE INDEX SYSROLES_INDEX1 ON SYSROLES (null);

CREATE UNIQUE INDEX SYSTRIGGERS_INDEX1 ON SYSTRIGGERS (null);

CREATE UNIQUE INDEX SQL110709131719690 ON LICENSE (null);

CREATE UNIQUE INDEX SYSPERMS_INDEX1 ON SYSPERMS (null);

CREATE UNIQUE INDEX SYSROUTINEPERMS_INDEX1 ON SYSROUTINEPERMS (null);

CREATE UNIQUE INDEX SYSFILES_INDEX2 ON SYSFILES (null);

CREATE INDEX SYSDEPENDS_INDEX2 ON SYSDEPENDS (null);

CREATE UNIQUE INDEX SYSFOREIGNKEYS_INDEX1 ON SYSFOREIGNKEYS (null);

CREATE INDEX SYSCOLPERMS_INDEX3 ON SYSCOLPERMS (null);

CREATE UNIQUE INDEX SYSTABLEPERMS_INDEX1 ON SYSTABLEPERMS (null);

CREATE INDEX SQL110709131720440 ON MODULEENTRY (null);

CREATE INDEX SQL110709131720290 ON COMPONENTENTRY (null);

CREATE INDEX SYSFOREIGNKEYS_INDEX2 ON SYSFOREIGNKEYS (null);

CREATE UNIQUE INDEX SYSALIASES_INDEX1 ON SYSALIASES (null);

CREATE INDEX SYSCONGLOMERATES_INDEX3 ON SYSCONGLOMERATES (null);

CREATE UNIQUE INDEX SYSROLES_INDEX3 ON SYSROLES (null);

CREATE UNIQUE INDEX SYSSTATEMENTS_INDEX1 ON SYSSTATEMENTS (null);

CREATE UNIQUE INDEX SYSCOLPERMS_INDEX1 ON SYSCOLPERMS (null);

CREATE INDEX SYSDEPENDS_INDEX1 ON SYSDEPENDS (null);

CREATE UNIQUE INDEX SYSCONGLOMERATES_INDEX2 ON SYSCONGLOMERATES (null);

CREATE INDEX SYSPERMS_INDEX2 ON SYSPERMS (null);

CREATE UNIQUE INDEX SYSTRIGGERS_INDEX2 ON SYSTRIGGERS (null);

CREATE INDEX SQL110709131720400 ON COMPONENTENTRY (null);

CREATE UNIQUE INDEX SYSSTATEMENTS_INDEX2 ON SYSSTATEMENTS (null);

CREATE INDEX SYSSTATISTICS_INDEX1 ON SYSSTATISTICS (null);

CREATE UNIQUE INDEX SYSTABLES_INDEX1 ON SYSTABLES (null);

CREATE UNIQUE INDEX SYSCONSTRAINTS_INDEX1 ON SYSCONSTRAINTS (null);

CREATE INDEX SYSROUTINEPERMS_INDEX3 ON SYSROUTINEPERMS (null);

CREATE UNIQUE INDEX SYSTABLES_INDEX2 ON SYSTABLES (null);

CREATE UNIQUE INDEX SQL110709131719310 ON CONF (null);

CREATE UNIQUE INDEX SYSCHECKS_INDEX1 ON SYSCHECKS (null);

CREATE UNIQUE INDEX SYSKEYS_INDEX1 ON SYSKEYS (null);

CREATE INDEX SQL110709131720420 ON MODULEENTRY (null);

CREATE UNIQUE INDEX SYSROUTINEPERMS_INDEX2 ON SYSROUTINEPERMS (null);

CREATE INDEX SYSCOLUMNS_INDEX2 ON SYSCOLUMNS (null);

CREATE UNIQUE INDEX SYSSCHEMAS_INDEX1 ON SYSSCHEMAS (null);

CREATE UNIQUE INDEX SYSFILES_INDEX1 ON SYSFILES (null);

CREATE UNIQUE INDEX SYSCONSTRAINTS_INDEX2 ON SYSCONSTRAINTS (null);

CREATE UNIQUE INDEX SQL110709131720160 ON MODULEENTRY (null);

CREATE UNIQUE INDEX SQL110709131719840 ON COMPONENTENTRY (null);

CREATE UNIQUE INDEX SQL110709131719480 ON ROLE (null);

CREATE INDEX SYSTRIGGERS_INDEX3 ON SYSTRIGGERS (null);

CREATE UNIQUE INDEX SYSPERMS_INDEX3 ON SYSPERMS (null);

CREATE INDEX SYSCONSTRAINTS_INDEX3 ON SYSCONSTRAINTS (null);

CREATE UNIQUE INDEX SYSALIASES_INDEX2 ON SYSALIASES (null);

CREATE UNIQUE INDEX SYSALIASES_INDEX3 ON SYSALIASES (null);

ALTER TABLE TAPESTRYVERSION ADD CONSTRAINT SQL110709131719090 PRIMARY KEY (ID);

ALTER TABLE COMPONENTENTRY ADD CONSTRAINT SQL110709131719840 PRIMARY KEY (ID);

ALTER TABLE LICENSE ADD CONSTRAINT SQL110709131719690 PRIMARY KEY (ID);

ALTER TABLE MODULEENTRY ADD CONSTRAINT SQL110709131720160 PRIMARY KEY (ID);

ALTER TABLE AUTO_PK_SUPPORT ADD CONSTRAINT SQL110709131720470 PRIMARY KEY (TABLE_NAME);

ALTER TABLE CONF ADD CONSTRAINT SQL110709131719310 PRIMARY KEY (ID);

ALTER TABLE ROLE ADD CONSTRAINT SQL110709131719480 PRIMARY KEY (ID);

ALTER TABLE COMPONENTENTRY ADD CONSTRAINT SQL110709131720290 FOREIGN KEY (ID)
	REFERENCES LICENSE (ID);

ALTER TABLE MODULEENTRY ADD CONSTRAINT SQL110709131720460 FOREIGN KEY (ID)
	REFERENCES TAPESTRYVERSION (ID);

ALTER TABLE MODULEENTRY ADD CONSTRAINT SQL110709131720440 FOREIGN KEY (ID)
	REFERENCES TAPESTRYVERSION (ID);

ALTER TABLE COMPONENTENTRY ADD CONSTRAINT SQL110709131720330 FOREIGN KEY (ID)
	REFERENCES TAPESTRYVERSION (ID);

ALTER TABLE MODULEENTRY ADD CONSTRAINT SQL110709131720420 FOREIGN KEY (ID)
	REFERENCES LICENSE (ID);

ALTER TABLE COMPONENTENTRY ADD CONSTRAINT SQL110709131720400 FOREIGN KEY (ID)
	REFERENCES TAPESTRYVERSION (ID);

