package org.apache.componentworld.entities.auto;

import java.util.List;

import org.apache.cayenne.ObjectContext;
import org.apache.cayenne.query.NamedQuery;
import org.apache.componentworld.entities.EntryType;
import org.apache.componentworld.entities.SourceType;

/**
 * This class was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public class _ComponentFinderMap {

    public static final String ENTRY_TYPES_QUERYNAME = "entryTypes";

    public static final String SOURCE_TYPES_QUERYNAME = "sourceTypes";

    public List<EntryType> performEntryTypes(ObjectContext context ) {
        return context.performQuery(new NamedQuery("entryTypes"));
    }

    public List<SourceType> performSourceTypes(ObjectContext context ) {
        return context.performQuery(new NamedQuery("sourceTypes"));
    }
}