package org.apache.componentworld.entities.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.componentworld.entities.Entry;
import org.apache.componentworld.entities.EntryType;
import org.apache.componentworld.entities.License;
import org.apache.componentworld.entities.SourceType;
import org.apache.componentworld.entities.TapestryVersion;

/**
 * Class _Entry was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
@SuppressWarnings("serial")
public abstract class _Entry extends CayenneDataObject {

    public static final String DEMONSTRATION_URL_PROPERTY = "demonstrationUrl";
    public static final String DESCRIPTION_PROPERTY = "description";
    public static final String DOCUMENTATION_URL_PROPERTY = "documentationUrl";
    public static final String ENABLED_PROPERTY = "enabled";
    public static final String FIRST_AVAILABLE_PROPERTY = "firstAvailable";
    public static final String ID_PROPERTY = "id";
    public static final String NAME_PROPERTY = "name";
    public static final String CHILDREN_PROPERTY = "children";
    public static final String ENTRY_TYPE_PROPERTY = "entryType";
    public static final String LICENSE_PROPERTY = "license";
    public static final String PARENT_PROPERTY = "parent";
    public static final String SINCE_PROPERTY = "since";
    public static final String SOURCE_TYPE_PROPERTY = "sourceType";
    public static final String UNTIL_PROPERTY = "until";

    public static final String ID_PK_COLUMN = "ID";

    public void setDemonstrationUrl(String demonstrationUrl) {
        writeProperty("demonstrationUrl", demonstrationUrl);
    }
    public String getDemonstrationUrl() {
        return (String)readProperty("demonstrationUrl");
    }

    public void setDescription(String description) {
        writeProperty("description", description);
    }
    public String getDescription() {
        return (String)readProperty("description");
    }

    public void setDocumentationUrl(String documentationUrl) {
        writeProperty("documentationUrl", documentationUrl);
    }
    public String getDocumentationUrl() {
        return (String)readProperty("documentationUrl");
    }

    public void setEnabled(Boolean enabled) {
        writeProperty("enabled", enabled);
    }
    public Boolean getEnabled() {
        return (Boolean)readProperty("enabled");
    }

    public void setFirstAvailable(Date firstAvailable) {
        writeProperty("firstAvailable", firstAvailable);
    }
    public Date getFirstAvailable() {
        return (Date)readProperty("firstAvailable");
    }

    public void setId(Integer id) {
        writeProperty("id", id);
    }
    public Integer getId() {
        return (Integer)readProperty("id");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void addToChildren(Entry obj) {
        addToManyTarget("children", obj, true);
    }
    public void removeFromChildren(Entry obj) {
        removeToManyTarget("children", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Entry> getChildren() {
        return (List<Entry>)readProperty("children");
    }


    public void setEntryType(EntryType entryType) {
        setToOneTarget("entryType", entryType, true);
    }

    public EntryType getEntryType() {
        return (EntryType)readProperty("entryType");
    }


    public void setLicense(License license) {
        setToOneTarget("license", license, true);
    }

    public License getLicense() {
        return (License)readProperty("license");
    }


    public void setParent(Entry parent) {
        setToOneTarget("parent", parent, true);
    }

    public Entry getParent() {
        return (Entry)readProperty("parent");
    }


    public void setSince(TapestryVersion since) {
        setToOneTarget("since", since, true);
    }

    public TapestryVersion getSince() {
        return (TapestryVersion)readProperty("since");
    }


    public void setSourceType(SourceType sourceType) {
        setToOneTarget("sourceType", sourceType, true);
    }

    public SourceType getSourceType() {
        return (SourceType)readProperty("sourceType");
    }


    public void setUntil(TapestryVersion until) {
        setToOneTarget("until", until, true);
    }

    public TapestryVersion getUntil() {
        return (TapestryVersion)readProperty("until");
    }


}
