package org.apache.componentworld.entities.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.componentworld.entities.Role;

/**
 * Class _User was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _User extends CayenneDataObject {

    public static final String ENABLED_PROPERTY = "enabled";
    public static final String FIRST_NAME_PROPERTY = "firstName";
    public static final String LAST_NAME_PROPERTY = "lastName";
    public static final String USER_ID_PROPERTY = "userId";
    public static final String ROLE_PROPERTY = "role";

    public static final String ID_PK_COLUMN = "ID";

    public void setEnabled(Boolean enabled) {
        writeProperty("enabled", enabled);
    }
    public Boolean getEnabled() {
        return (Boolean)readProperty("enabled");
    }

    public void setFirstName(String firstName) {
        writeProperty("firstName", firstName);
    }
    public String getFirstName() {
        return (String)readProperty("firstName");
    }

    public void setLastName(String lastName) {
        writeProperty("lastName", lastName);
    }
    public String getLastName() {
        return (String)readProperty("lastName");
    }

    public void setUserId(String userId) {
        writeProperty("userId", userId);
    }
    public String getUserId() {
        return (String)readProperty("userId");
    }

    public void setRole(Role role) {
        setToOneTarget("role", role, true);
    }

    public Role getRole() {
        return (Role)readProperty("role");
    }


}
